### ISSUE TITLE
is it not working properly 

### ISSUE THREAD

**Issue by RishabhBhatt19247** [Mr-Amit/Disease-Prediction-Using-MLwithDjango#1]
It gives different disease name in different session with same symptoms , how can this possible.
can you please explain this.

**Comment by Mr-Amit** [comment]
Since our dataset is small and has 50+ diseases and symptoms, with almost a unique combination of symptoms for every disease, which raises the uncertainty for predicting a disease (since fewer cases support the same)

Because of this
the algorithms which use randomness for predicting like randomForest and trainTestSplit(splits data randomly), the results get skewed slightly.
